config/routes.rb
Railsblog7::Application.routes.draw do
  devise_for :users 
  resources :users, :only => [:index, :show] do
    resources :comments, :only => [:index]
  end
  resources :posts do
	resources :comments, :only => [:index, :new, :create]
  end

  root :to => 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, [User, Post, Comment]
    elsif user.role == 'author'
			can [:read, :create, :update], [User, Post, Comment]
			can [:destroy], Post
	  # can :manage, Session
		else
			can :read, [Post, Comment]
			can :update, Post
			can :create, Comment
	  # can :manage, Session
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :post_id
  validates :user_id, presence: true
  
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :comments_attributes
  validates :title, presence: true, length: { maximum: 55 }
  validates :content, presence: true
    
  belongs_to :user
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments
	
	def self.search(search)
		if search
			where('title LIKE ?', "%#{search}%")
		else
			scoped
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me, :role, :postanonymous, :bio, :twitter

  validates :name, presence: true, uniqueness: true, length: { maximum: 40 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :role, :inclusion => { :in => %w(admin author reader), :message => "must be admin, author (requires admin approval) or reader" }
  
  # scope :in_AtoZ, order('name ASC')
  scope :avidreader, select('users.id, count(comments.id) AS comment_count').
						joins(:comments).
						group('users.id').
						order('comment_count DESC').
						limit(4)

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  check_authorization :unless => :devise_controller?
  
  private
  
  def set_current_user
	if user_signed_in?
		@user = current_user
	else
		redirect_to new_user_session_path
	end
  end
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to posts_path, :alert => exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :post
  load_and_authorize_resource :through => :post

  skip_authorize_resource :only => :show  
  skip_authorize_resource :post, :only => :show
  
  before_filter :set_current_user
  
  def index
	@user = User.find(params[:user_id])
	@comments = @user.comments
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check
  
  def index
	@users = User.all
	@post = Post.last
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_filter :find_post, except: [:index, :new, :create]
  before_filter :set_current_user
	respond_to :html, :js
  
  def index
		@posts = Post.search(params[:search]).paginate(:page => params[:page], :per_page => 3)
  end

  def show
		@comments = @post.comments.order('created_at DESC')
		@newcomment = @post.comments.new
  end

  def new
		@post = Post.new
  end

  def create
		@post = Post.new(params[:post])
		@post.user_id = @user.id
		if @post.save
			redirect_to @post
		else
			render :edit
		end
  end

  def edit
  end

  def update
		# if comment
		if params[:post].has_key?(:comments_attributes)
			params[:post][:comments_attributes]['0'][:user_id] = @user.id
			comments_flag = true
		end

		if !comments_flag #if not set, we're editing the post
			if @post.update_attributes(params[:post])
				redirect_to @post #render full show template
			else
				render :edit
			end
		elsif comments_flag #if set, we're only adding a comment (nested attribute)
			if @post.update_attributes(params[:post])
				@comments = @post.comments.order('created_at DESC')
				respond_with @comments, :location => post_path(@post)
			else
				flash[:error] = "Error submitting comment. Try again or contact sysadmin"
				redirect_to @post
			end
		end
  end

  def destroy
		if @post.destroy
#			redirect_to posts_path <- this was the old non-AJAX command
			respond_to do |format|
				format.js {}
			end
		else
			flash[:error] = "Error deleting post. Try again or contact sysadmin"
			redirect_to @post
		end
  end
  
  def find_post
		@post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
	helper_method :sort_column, :sort_direction
  
  def index
		@users = User.order(sort_column + " " + sort_direction)
		@avids = User.avidreader.map{|u| u.id}
  end

  def show
		@user = User.find(params[:id])
  end

  def new
		@user = User.new
  end

  def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to @user
		else
			render :edit
		end
  end

  def edit
		@user = User.find(params[:id])	
  end

  def update
  	@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to @user
		else
			render :edit
		end
  end

  def destroy
  	@user = User.find(params[:id])
		if @user.destroy
			redirect_to users_path
		else
			flash[:error] = "Error deleting user. Try again or contact sysadmin"
			redirect_to @user
		end
  end
	
	private
  
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Based on https://gist.github.com/1182136
  class BootstrapLinkRenderer < ::WillPaginate::ActionView::LinkRenderer
    protected
 
    def html_container(html)
      tag :div, tag(:ul, html), container_attributes
    end
 
    def page_number(page)
      tag :li, link(page, page, :rel => rel_value(page)), :class => ('active' if page == current_page)
    end
 
    def gap
      tag :li, link(super, '#'), :class => 'disabled'
    end
 
    def previous_or_next_page(page, text, classname)
      tag :li, link(text, page || '#'), :class => [classname[0..3], classname, ('disabled' unless page)].join(' ')
    end
  end
 
  def page_navigation_links(pages)
    will_paginate(pages, :class => 'pagination', :inner_window => 2, :outer_window => 0, :renderer => BootstrapLinkRenderer, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe)
  end
	
	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, params.merge(:sort => column, :direction => direction, :remote => true), {:class => css_class}
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>Comments by <%= @user.name %>:</h1>


<% @comments.each do |comment| %>
 <div class='well'>
    <p><%= comment.content %></p>
	<p class="pull-right">in response to '<%= comment.post.title %>'</p>
 </div>
<% end %>
</table>

<br />

app/views/home/index.html.erb
<h1>Welcome!</h1>
<h3>Most recent post:</h3>
<h4><%= @post.title %></h4>
<p><%= @post.content[0..100] %>... (<%= link_to 'more', @post %>)</p>
<p></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsblog7</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="row">
  <div class="navbar navbar-inverse navbar-static-top">
	<div class="navbar-inner">
	  <ul class="nav" style="margin-left: 100px;">
		<li><%= link_to 'Home', root_url %></li>
		<li><%= link_to 'All Posts', posts_path %></li>
		<li><%= link_to 'New Post', new_post_path %></li>
		<li><%= link_to 'Users', users_path %></li>
		<li>
	  </ul>
	  <ul class="nav pull-right" style="margin-right: 50px;">
		<li>
		  <% if user_signed_in? %>
			<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		  <% else %>
			<%= link_to "sign in", new_user_session_path %>
		  <% end %>
		</li>
	  </ul>
	</div>
		<div class="pull-right" style="font-size: 80%; margin-right: 69px;">
		  <% if user_signed_in? %>
			Signed in as <%= current_user.email %>. Not you?
		  <% end %>
		</div>
  </div>
 </div>
 <div class="container">
	<div class="row">
	  <div class="container">
 	   <div class="span12">
		  <div class="well">
		   <div class="media">
			<a class="pull-left" href="#">
			  <img src="/assets/firefly90x90.png">
			</a>		   
		    <div class="media-body">
				<h2>Firefly Fan Forum</h2>
				<p>All the news that is fit to print about the best sci-fi series on TV (other than Battlestar Galactica)</p>
		    </div>
		   </div>
		  </div>
	   </div>
	  </div>  
	</div>

	<div class="row">
	  <div class="span3">
		<div class="nav nav-tabs nav-stacked">
		  <li><a href="#">Firefly, the show</a></li>
		  <li><a href="#">Serenity, the movie</a></li>
		  <li><a href="#">Firefly cast</a></li>
		  <li><a href="#">Firefly lore</a></li>
		  <li><a href="#">NASA</a></li>
		</div>
	  </div>
	  <div class="span9">
		<%= yield %>
	  	 </div>
	</div>
 </div>
 <div class='container'>
	<p style='margin-top: 40px; text-align: center;'>&copy; Kevin Browne, 2013. All rights reserved.</p>
 </div>

</body>
</html>

app/views/posts/_comments.html.erb
<table class='table table-striped'>
	<% @comments.each do |comment| %>
		<tr>
			<% if comment.user_id.nil? %>
				<td>name withheld</td>
			<% elsif comment.user.postanonymous == true %>
				<td>Anonymous</td>
			<% else %>
				<td><%= link_to comment.user.name, user_comments_path(comment.user) %></td>
			<% end %>
				<td><%= comment.content %> (posted at <%= comment.created_at.strftime("%m/%d/%Y") %>)</td>
		</tr>
	<% end %>
</table>

app/views/posts/_post.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, :required => true, :autofocus => true, :input_html => { :class => "span5" } %>
    <%= f.input :content, :as => :text, :input_html => { :class => "span6", :rows => 12} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit Post", { :class => "btn btn-success" } %>
	<%= link_to "Cancel and return to All Posts", posts_path, { :class => "btn btn-primary" } %>
  </div>
<% end %>

app/views/posts/_postlist.html.erb
<% @posts.each do |post| %>
    <div class="well">
		<h3><%= link_to post.title, post %></h3>
		<p><%= post.content[0..100] %>... (more) </p>
		<p><span style="font: italic 10px serif;">Last updated: <%= post.updated_at %></span> &emsp; | &emsp; <span style="color: #cc0000;"><%= post.comments.count %> comments</span></p>
		<p>
		  <% if can? :update, Post %>
			<%= link_to 'Edit', edit_post_path(post), { :class => "btn btn-mini btn-warning" } %>
		  <% end %>
		  <% if can? :destroy, Post %>
		    <%= link_to 'Delete', post, class: 'btn btn-mini btn-danger', method: :delete, :remote => true, confirm: 'Are you sure?' %>
		  <% end %>
		</p>
	</div>
<% end %>
<%= will_paginate @posts, :remote => true %>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <div class="well" id="post<%= post.id %>">
		<h3><%= link_to post.title, post %></h3>
		<p><%= post.content[0..100] %>... (more) </p>
		<p><span style="font: italic 10px serif;">Last updated: <%= post.updated_at %></span> &emsp; | &emsp; <span style="color: #cc0000;"><%= post.comments.count %> comments</span></p>
		<p>
		  <% if can? :update, Post %>
			<%= link_to 'Edit', edit_post_path(post), { :class => "btn btn-mini btn-warning" } %>
		  <% end %>
		  <% if can? :destroy, Post %>
		    <%= link_to 'Delete', post, class: 'btn btn-mini btn-danger', method: :delete, :remote => true, confirm: 'Are you sure?' %>
		  <% end %>
		</p>
	</div>
<% end %>
<%= will_paginate @posts %>

app/views/posts/destroy.js.erb
$("#post<%= @post.id %>").fadeOut();

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class='form-horizontal'>
  <%= render :partial => 'post', :locals => { :post => @post } %>
</div>

<p></p>

app/views/posts/index.html.erb
<div>
	<h3>Posts
		<div class='pull-right'> 
			<%= form_tag posts_path, :method => :get, :remote => true, :id => "posts_search" do %>
				<%= text_field_tag :search, params[:search], :label => false%>
				<span class="add-on"><i class="icon-search icon-white"></i></span>
			<% end %>
		</div>
	</h3>
</div>

<div id="postlist"><%= render 'posts' %></div>


<hr />
<% if can? :create, @post %>
  <%= link_to 'New Post', new_post_path, { :class => "btn btn-success" } %>
<%end %>

app/views/posts/index.js.erb
$("#postlist").html("<%= escape_javascript(render('posts')) %>");
$.setAjaxPagination();

app/views/posts/new.html.erb
<h1>Create a new Post</h1>


<div class='form-horizontal'>
  <%= render :partial => 'post', :locals => { :post => @post } %>
</div>

<p></p>

app/views/posts/show.html.erb
<div id="content">
  <input type="button" value="Hide" id="toggleButton" style="float:right;">
  <h2><%= @post.title %></h2>
	<p id="sigline">by <%= @post.user.name %></p>

	<p id ="bodycontent"><%= @post.content %><br />

	Last updated: <%= @post.updated_at.strftime("%m/%d/%Y") %></p>
</div>

<div id="newcomment">
	<h2>Comments</h2>

	<h5><%= @user.name %>, comment on this post</h5>
	<%= simple_form_for @post, :remote => true do |f| %>
		<%= f.simple_fields_for :comments, @newcomment do |nc| %>
		<p>
			<%= nc.input :content, :as => :text, :label => false, :input_html => { :class => "span6", :rows => 6} %>
		</p>
		<% end %>
		<p>
			<%= f.submit "Comment", { :class => "btn btn-success" } %>
		</p>
	<% end %>
</div>

<div id="commentlist"><%= render 'comments' %></div>

	<hr />
	<p>
		<% if can? :update, @post %>
			<%= link_to 'Edit this post', edit_post_path, { :class => "btn btn-warning" } %>
		<% end %>
	</p>
	<p></p>
	<p><%= link_to "<- Back to All Posts", posts_path, { :class => "btn btn-primary" } %></p>

app/views/posts/show.js.erb
$("#commentlist").html("<%= escape_javascript(render('comments')) %>");

app/views/posts/update.js.erb
$("#commentlist").html("<%= escape_javascript(render('comments')) %>");

app/views/users/_user.html.erb
	<table class='table table-striped'>
		<tr>
			<th><%= sortable "name" %></th>
			<th><%= sortable "email" %></th>
			<th><%= sortable "twitter" %></th>
			<th><%= sortable "role" %></th>
			<th>Bio</th>
		</tr>
	<% @users.each do |user| %>
		<tr>
			<td><%= if @avids.include?(user.id) then "*" end %> <%= link_to user.name, user %></td>
			<td><%= user.email %></td>
			<td><%= user.twitter %></td>
			<td><%= user.role %></td>
			<td><%= user.bio %></td>
		</tr>
	<% end %>
	</table>
	<p><i>* - indicates top commenter</i></p>

app/views/users/index.html.erb
<h1>List of Users</h1>

<div id="userlist"><%= render 'user' %></div>

app/views/users/index.js.erb
$("#userlist").html("<%= escape_javascript(render('user')) %>");

app/views/users/show.html.erb
<h1>User Info <%= link_to 'Edit', edit_user_registration_path(@user), { :class => "btn btn-warning" } %></h1>
<p>&nbsp;</p>
<table class='table table-bordered table-condensed'>
  <tr>
	<td>Name</td><td><%= @user.name %></td>
  </tr>
  <tr>
	<td>Email</td><td><%= @user.email %></td>
  </tr>
  <tr>
	<td>Twitter</td><td><%= @user.twitter %></td>
  </tr>
  <tr>
	<td>Bio</td><td><%= @user.bio %></td>
  </tr>
  <tr>
	<td>Role</td><td><%= @user.role %></td>
  </tr>
</table>	
<br />
<p><%= link_to "<- Back to All Users", users_path, { :class => "btn btn-primary" } %></p>
<p></p>

<hr />
<h4>Posts by <%= @user.name %></h4>

<% @user.posts.each do |post| %>
    <p><%= link_to post.title, post_path(post) %></p>
<% end %>